In [1]:
import torch

In [ ]:
bs=4
q_next = torch.rand((bs,2))

In [5]:
q_next

tensor([[0.7533, 0.7512],
        [0.8241, 0.0977],
        [0.0218, 0.0333],
        [0.0119, 0.3092]])

In [6]:
q_next.max(dim=1).values

tensor([0.7533, 0.8241, 0.0333, 0.3092])

In [ ]:
gamma=0.95

r=10

q_next_max = q_next.max(dim=1).values

y = r + gamma * q_next_max

y

tensor([10.7156, 10.7829, 10.0316, 10.2937])

In [8]:
q_all = torch.rand((bs,2))

In [ ]:
actions = torch.rand((bs,2))<0.5

In [18]:
actions

tensor([[False, False],
        [False,  True],
        [ True,  True],
        [False,  True]])

In [19]:
actions.long()

tensor([[0, 0],
        [0, 1],
        [1, 1],
        [0, 1]])

In [32]:
action_idx = actions.long().argmax(dim=1)

In [33]:
print(action_idx.shape)
print(action_idx.unsqueeze(1).shape)

torch.Size([4])
torch.Size([4, 1])


In [34]:
q_all.gather(1, action_idx.unsqueeze(1)).squeeze(1)

tensor([0.5421, 0.8464, 0.4439, 0.5364])

In [ ]:
q_current = q_all.gather(1, action_idx.unsqueeze(1)).squeeze(1)

In [ ]:

q_current = q_all.gather(1, action_idx.unsqueeze(1)).squeeze(1)

loss = ((y - q_current).pow(2)).mean()